[workspace]
members = [ "crates/*" ]
exclude = [ "files", "crates/aquascope_serve" ]
resolver = "2"

# Make snapshot testing faster
[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
