[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.watch-front]
script = "cargo watch -i frontend -x 'install --path crates/aquascope_front --offline --locked'"

[tasks.watch-mdbook]
script = "cargo watch -w crates/mdbook-aquascope/src -w frontend/packages/embed/dist --no-vcs-ignores -x 'install --path crates/mdbook-aquascope --locked --debug --offline'"

[tasks.watch.run_task]
name = ["watch-front", "watch-mdbook"]
parallel = true

[tasks.init-bindings]
script = """
cargo run --bin export-ts --locked
cargo test -p aquascope -p mdbook-aquascope --lib export_bindings --locked
mkdir -p frontend/packages/types/src/bindings
cp crates/**/bindings/* frontend/packages/types/src/bindings
"""

[tasks.install-aquascope]
dependencies = ["init-bindings"]
script = """
cd frontend && depot build && cd ..
cargo miri setup
cargo install --path crates/aquascope_front --locked
"""

[tasks.install-mdbook]
dependencies = ["install-aquascope"]
script = "cargo install --path crates/mdbook-aquascope --locked"

[tasks.playground-front]
script = """
export MIRI_SYSROOT=$(cargo miri setup --print-sysroot)
cd frontend && depot build -w
"""

[tasks.playground.run_task]
dependencies = ["install-aquascope"]
name = ["watch-server", "playground-front"]
parallel = true
